version: "3"
services:
  minio:
    image: minio/minio
    expose:
      - "9000"
    container_name: mlflow_s3
    ports: #publish ports to host
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    environment: # -e options
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    networks:
      - mlflow-network
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    # Note there is no bucket by default
    command: server /data --console-address ":9001"

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - mlflow-network
    requests:
      cpu: "0.1"
      memory: "128M"
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 user password &&
      if ! mc ls minio/bucket; then
        mc mb minio/bucket
      else
        echo 'bucket already exists'
      fi
      "

  postgres:
    image: postgres
    restart: always
    container_name: mlflow_postgres
    networks:
      - mlflow-network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  tracking-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio-create-bucket
    expose:
      - "5000"
    networks:
      - mlflow-network
    ports:
      # MLflow UI is available at http://localhost:5000
      - "5000:5000"
    environment:
      MLFLOW_SERVER_ENABLE_JOB_EXECUTION: "false"
      MLFLOW_SERVER_DISABLE_SECURITY_MIDDLEWARE: "true"
      AWS_ACCESS_KEY_ID: "user"
      AWS_SECRET_ACCESS_KEY: "password"
      MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
    container_name: mlflow_server
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://user:password@postgres:5432/db
      --default-artifact-root s3://bucket
      --gunicorn-opts "--log-level debug"

networks:
  mlflow-network:
    external: true